/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapProjectsDotxmlRouteImport } from './routes/sitemap-projects[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ApiOgProjectsSlugRouteImport } from './routes/api/og/projects.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapProjectsDotxmlRoute = SitemapProjectsDotxmlRouteImport.update({
  id: '/sitemap-projects.xml',
  path: '/sitemap-projects.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const ApiOgProjectsSlugRoute = ApiOgProjectsSlugRouteImport.update({
  id: '/api/og/projects/$slug',
  path: '/api/og/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-projects.xml': typeof SitemapProjectsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/og/projects/$slug': typeof ApiOgProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-projects.xml': typeof SitemapProjectsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/og/projects/$slug': typeof ApiOgProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-projects.xml': typeof SitemapProjectsDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/og/projects/$slug': typeof ApiOgProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/services'
    | '/sitemap-pages.xml'
    | '/sitemap-projects.xml'
    | '/sitemap.xml'
    | '/projects/$slug'
    | '/services/$slug'
    | '/api/og/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/services'
    | '/sitemap-pages.xml'
    | '/sitemap-projects.xml'
    | '/sitemap.xml'
    | '/projects/$slug'
    | '/services/$slug'
    | '/api/og/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/services'
    | '/sitemap-pages.xml'
    | '/sitemap-projects.xml'
    | '/sitemap.xml'
    | '/projects/$slug'
    | '/services/$slug'
    | '/api/og/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapProjectsDotxmlRoute: typeof SitemapProjectsDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiOgProjectsSlugRoute: typeof ApiOgProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-projects.xml': {
      id: '/sitemap-projects.xml'
      path: '/sitemap-projects.xml'
      fullPath: '/sitemap-projects.xml'
      preLoaderRoute: typeof SitemapProjectsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/api/og/projects/$slug': {
      id: '/api/og/projects/$slug'
      path: '/api/og/projects/$slug'
      fullPath: '/api/og/projects/$slug'
      preLoaderRoute: typeof ApiOgProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapProjectsDotxmlRoute: SitemapProjectsDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiOgProjectsSlugRoute: ApiOgProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
